### PR TITLE
Change waterfall type and other small fixes

### LINKED ISSUE #99: Allow users to enter State Pension in Your household
Unless it's calculated only? If so, let's clarify that in the Pension income section:
image

### LINKED ISSUE #219: Remove "/year" from land value household input
e.g. should just be £12116
image

### LINKED ISSUE #224: Remove single-family household label for now

### LINKED ISSUE #227: Replace provision waterfall chart with program waterfall chart
Only report changes to taxes, benefits (including UBI), and overall.

This will speed up calculations and avoid complications with sequencing and grouping reform provisions, and matching that to the waterfall (currently the waterfall is sequenced differently from the actual reform sequence).

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
* Changes waterfall type to tax and benefit
* Renames the package name to include UK
* Fixes #219 
* Fixes #224

### CODE REVIEW

File: client/src/js/pages/policy/default_policy.js [hunk 1]
```diff
@@ -236,6 +236,15 @@ const DEFAULT_POLICY = {
 		summary: "Abolish State Pension",
 		type: "abolish"
 	},
+	UC_single_young: {
```
Comment (MaxGhenis) [inline client/src/js/pages/policy/default_policy.js:239]: Feels incomplete to only include the 18-25 one. Could you add other standard allowances?

File: policy_engine_uk/situations/charts.py [hunk 2]
```diff
@@ -105,15 +105,14 @@ def get_mtr(x, y):
...
-    net_income += [reformed.calc("net_income").sum()]
-    net_income = np.array(net_income)
-    budget_effects = net_income[1:] - net_income[:-1]
+    GROUPS = ["benefits", "tax"]
+    MULTIPLIERS = [1, -1]
+    effects = [
+        (reformed.calc(var).sum() - baseline.calc(var).sum()) * multiplier
+        for var, multiplier in zip(GROUPS, MULTIPLIERS)
+    ]
     fig = waterfall(
```
Comment (MaxGhenis) [inline policy_engine_uk/situations/charts.py:114]: It looks like this shows taxes and benefits even if they're zero, is that right? This would be my suggestion, so just confirming.

File: policy_engine/reset_cache.py [hunk 3]
```diff
@@ -1,6 +0,0 @@
-from google.cloud import storage
```
Comment (MaxGhenis) [inline policy_engine/reset_cache.py]: Did another part of this PR replace this cache resetting?

File: policy_engine_uk/situations/charts.py (hunk 2 above)
Comment (nikhilwoodruff) [reply policy_engine_uk/situations/charts.py:114]: Yep, that's right

File: client/src/js/pages/policy/default_policy.js (hunk 1 above)
Comment (nikhilwoodruff) [reply client/src/js/pages/policy/default_policy.js:239]: Added!

File: policy_engine/reset_cache.py (hunk 3 above)
Comment (nikhilwoodruff) [reply policy_engine/reset_cache.py]: Oh my mistake, re-added
